name: Ejecutor de Analitica Predictiva
on:
  schedule:
    - cron: '*/15 * * * *' # Se ejecuta de forma automática cada 15 minutos
  workflow_dispatch: # Te permite picar un botón para ejecutarlo manualmente cuando quieras

jobs:
  run-analytics:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar Repositorio
        uses: actions/checkout@v3

      - name: Configurar Entorno Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Ejecutar Motor de Entropía
        run: python src/engine.py

      - name: Guardar Cambios en JSON
        run: |
          git config --global user.name 'PredictiveBot'
          git config --global user.email 'bot@predictive.local'
          git add data/state.json
          git commit -m "Auto-actualización de métricas telemétricas [Bot]" || echo "No hay cambios en los datos"
          git push
